{
 "title": "DASH SAMPLE",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Advanced Monitoring Purchases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantity of Enrollment (12 months) Month by Month - v1.0",
   "type": "timeseries",
   "description": "Number of registrations made in the last 12 months separated by origin (app, website) month by month",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  \tUNIX_TIMESTAMP(createdAt) as time_sec,\n\tDATE_FORMAT(createdAt, '%m') AS MonthNumber,\n\tSUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) AS Month,\n\tDATE_FORMAT(createdAt, '%Y') AS Year,\n\tCONCAT(SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3), '/' , DATE_FORMAT(createdAt, '%Y')) AS MonthYear,\n\t(SELECT COUNT(id) FROM purchases WHERE origin = 'app' AND SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) = Month AND DATE_FORMAT(createdAt, '%Y') = Year) AS App,\n\t(SELECT COUNT(id) FROM purchases WHERE origin = 'website' AND SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) = Month AND DATE_FORMAT(createdAt, '%Y') = Year) AS Website\nFROM\n\tpurchases \nWHERE\n\torigin IN('app', 'website') AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND NOW()\nGROUP BY\n\tMonthNumber, Year, Month, MonthYear \nORDER BY\n\tYear, MonthNumber, Month;\n"
    }
   ]
  },
  {
   "title": "Quantity of Enrollment (12 months) Month by Month",
   "type": "barchart",
   "description": "Number of registrations made in the last 12 months separated by origin (app, website) month by month",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n\tDATE_FORMAT(createdAt, '%m') AS MonthNumber,\n\tSUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) AS Month,\n\tDATE_FORMAT(createdAt, '%Y') AS Year,\n\tCONCAT(SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3), '/' , DATE_FORMAT(createdAt, '%Y')) AS MonthYear,\n\t(SELECT COUNT(id) FROM purchases WHERE origin = 'app' AND SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) = Month AND DATE_FORMAT(createdAt, '%Y') = Year) AS App,\n\t(SELECT COUNT(id) FROM purchases WHERE origin = 'website' AND SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) = Month AND DATE_FORMAT(createdAt, '%Y') = Year) AS Website\nFROM\n\tpurchases \nWHERE\n\torigin IN('app', 'website') AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND NOW()\nGROUP BY\n\tMonthNumber, Year, Month, MonthYear\nORDER BY\n\tYear, MonthNumber, Month;\n"
    }
   ]
  },
  {
   "title": "Percentage of Purchases (12 months)",
   "type": "piechart",
   "description": "Percentage of purchases in the last 12 months (month to month)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tDATE_FORMAT(createdAt, '%m') AS MonthNumber,\n\tSUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) AS Month,\n\tDATE_FORMAT(createdAt , '%Y') AS Year,\n\tCOUNT(id) AS Quantity,\n\tCONCAT(FORMAT(((COUNT(id) / (SELECT COUNT(*) FROM purchases WHERE createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW()))) * 100), 2), '%') AS Percentage\nFROM \n\tpurchases\nWHERE \n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())\nGROUP BY\n\tMonthNumber, Year, Month\nORDER BY \n\tYear, MonthNumber;\n"
    }
   ]
  },
  {
   "title": "Average of Purchases (12 months)",
   "type": "bargauge",
   "description": "Average purchases for the last 12 months",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT _Average_ FROM(\n\tSELECT\n\t\t(SELECT COUNT(*) FROM purchases WHERE createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) AS _Total_,\n\t\tSUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) AS _Month_,\n\t\tDATE_FORMAT(createdAt , '%Y') AS _Year_,\n\t\tCOUNT(id) AS _Quantity_,\n\t\tFORMAT((SELECT COUNT(*) FROM purchases WHERE createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) / (SELECT COUNT(_COUNTER_) FROM (\n\t\t\tSELECT COUNT(*) AS _COUNTER_, SUBSTR(DATE_FORMAT(createdAt, '%M'), 1, 3) AS _M_ FROM purchases WHERE createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW()) GROUP BY _M_\n\t\t) AS _VIRTUAL_), 0) AS _Average_\n\tFROM \n\t\tpurchases\n\tWHERE \n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())\n\tGROUP BY\n\t\t_Month_, _Year_\n) AS _Average_Calc_\nGROUP BY _Average_;"
    }
   ]
  },
  { "title": "Origin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Quantity of Sales Products By App",
   "type": "stat",
   "description": "Number of purchases made through the APP",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Total, now() AS time  FROM purchases p WHERE origin = 'app';"
    }
   ]
  },
  {
   "title": "Quantity of Sales Products By Website",
   "type": "stat",
   "description": "Number of purchases made through the Website",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Total, now() AS time  FROM purchases p WHERE origin = 'website';"
    }
   ]
  },
  {
   "title": "Quantity of Sales Products (12 months)",
   "type": "stat",
   "description": "Number of products sold (12 months)",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS time,\n\tSUM(quantity) AS TOTAL\nFROM\n\tpurchases\nWHERE\n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW());"
    }
   ]
  },
  {
   "title": "Quantity of users without purchases",
   "type": "stat",
   "description": "Number of registrations without purchases",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS time,\n\tCOUNT(u.id) as TOTAL\nFROM\n\tusers u\nWHERE\n\tu.id NOT IN (SELECT user_id  FROM purchases);\n"
    }
   ]
  },
  {
   "title": "Quantity of Purchases App x Website",
   "type": "bargauge",
   "description": "Quantity of purchases made through the App vs. Website",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(*) AS Total,\n\t(SELECT COUNT(*) FROM purchases p WHERE origin = 'app') AS App,\n\t(SELECT COUNT(*) FROM purchases p WHERE origin = 'website') AS Website\nFROM \n\tpurchases\nWHERE\n\tcreatedAt IS NOT NULL;\n\t"
    }
   ]
  },
  {
   "title": "Percentage of Purchases App x Website",
   "type": "gauge",
   "description": "Percentage of purchases made through the App vs. Website",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tFORMAT((((SELECT COUNT(*) FROM purchases p WHERE origin = 'app') / COUNT(*)) * 100), 0) AS App,\n\tFORMAT((((SELECT COUNT(*) FROM purchases p WHERE origin = 'website') / COUNT(*)) * 100), 0) AS Website\nFROM \n\tpurchases\nWHERE\n\tcreatedAt IS NOT NULL;\n\t"
    }
   ]
  },
  {
   "title": "Quantity of Purchases App x Website (12 months)",
   "type": "bargauge",
   "description": "Quantity of purchases made through the App vs. Website in the last 12 months",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(*) AS Total,\n\t(SELECT COUNT(*) FROM purchases p WHERE origin = 'app' AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) AS App,\n\t(SELECT COUNT(*) FROM purchases p WHERE origin = 'website' AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) AS Website\nFROM \n\tpurchases\nWHERE\n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW());\n"
    }
   ]
  },
  {
   "title": "Percentage of Purchases App x Website (12 months)",
   "type": "gauge",
   "description": "Percentage of purchases made through the App vs. Website in the last 12 months",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tFORMAT((((SELECT COUNT(*) FROM purchases p WHERE origin = 'app' AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) / COUNT(*)) * 100), 0) AS App,\n\tFORMAT((((SELECT COUNT(*) FROM purchases p WHERE origin = 'website' AND createdAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())) / COUNT(*)) * 100), 0) AS Website\nFROM \n\tpurchases\nWHERE\n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW());\n"
    }
   ]
  },
  { "title": "Purchases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Purchases Canceled (last 3 years)",
   "type": "stat",
   "description": "Number of purchases canceled in the last 3 years (accounted for by year: year1=200, year2=100, year3=500)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  (NOW()) as time,\n\tCOUNT(*) AS TOTAL,\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 3 YEAR)) AND ((NOW() - INTERVAL 2 YEAR))\n\t\tAND deletedAt IS NOT NULL\n\t) AS '2020',\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 2 YEAR)) AND ((NOW() - INTERVAL 1 YEAR))\n\t\tAND deletedAt IS NOT NULL\n\t) AS '2021',\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())\n\t\tAND deletedAt IS NOT NULL\n\t) AS '2022'\nFROM\n\tpurchases\nWHERE\n\tdeletedAt IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Total Purchases",
   "type": "gauge",
   "description": "Quantity of purchases in the grand total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Purchases, now() as time FROM users;"
    }
   ]
  },
  {
   "title": "Total Purchases (12 months)",
   "type": "gauge",
   "description": "Number of purchases in the last 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(*) AS Purchases, \n\t(NOW()) as time,\n\t(NOW() - INTERVAL 1 YEAR) AS _FROM_,\n\t(NOW()) as _TO_\nFROM \n\tpurchases \nWHERE\n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW());"
    }
   ]
  },
  {
   "title": "Total Purchases (last 3 years)",
   "type": "bargauge",
   "description": "Number of purchases in the last 3 years (accounted for by year: year1=200, year2=100, year3=500)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\t(NOW()) as time,\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 3 YEAR)) AND ((NOW() - INTERVAL 2 YEAR))\n\t) AS 'YEAR1',\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 2 YEAR)) AND ((NOW() - INTERVAL 1 YEAR))\n\t) AS 'YEAR2',\n\t(\n\tSELECT \n\t\tCOUNT(*)\n\tFROM \n\t\tpurchases \n\tWHERE\n\t\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())\n\t) AS 'YEAR3'\nFROM\n\tpurchases\nWHERE\n\tcreatedAt IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Total Canceled Purchases",
   "type": "stat",
   "description": "Number of canceled purchases",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Purchases, now() as time FROM purchases WHERE deletedAt IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Total Canceled Purchases (12 months)",
   "type": "stat",
   "description": "Number of purchases canceled in the last 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tCOUNT(*) As Purchases,\n\t(NOW()) as time,\n\t(NOW() - INTERVAL 1 YEAR) AS _FROM_,\n\t(NOW()) as _TO_\nFROM \n\tpurchases \nWHERE\n\tcreatedAt BETWEEN ((NOW() - INTERVAL 1 YEAR)) AND (NOW())\n\tAND deletedAt IS NOT NULL;\n\n"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Enrollment Users",
   "type": "gauge",
   "description": "Number of registrations performed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Users, now() as time FROM users;"
    }
   ]
  },
  {
   "title": "Deleted Users",
   "type": "gauge",
   "description": "Number of deleted records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Users, NOW() AS time FROM users WHERE deletedAt IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "gauge",
   "description": "Number of deleted records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Users, NOW() AS time FROM users WHERE active = 'yes';"
    }
   ]
  },
  {
   "title": "Inactive Users",
   "type": "gauge",
   "description": "Number of deleted records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS Users, NOW() AS time FROM users WHERE active = 'no';"
    }
   ]
  }
 ]
}